name: My Creative Website

# Handling reading
exclude: ["gulpfile.js", "package-lock.json", "package.json"]

collections:
  collections_dir: my_collections
  portfolio:

sass:
  sass_dir: _sass
  style: nested
