name: My Creative Website

# Handling reading
exclude: ["gulpfile.js", "package-lock.json", "package.json","Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]

# Defaults
collections_dir: my_collections
collections:
  portfolio:

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /my_collections/:year/:month/:title:output_ext
      author: "Gonçalo"

# CloudCannon
_explore:
  groups:
    - heading: Blogging
      collections:
        - posts
        - drafts
    - heading: Pages
      collections:
        - pages
    - heading: Data
      collections:
        - portfolio

# Vendor specific
sass:
  sass_dir: _sass
  style: nested
