name: My Creative Website

# Handling reading
exclude: ["gulpfile.js", "package-lock.json", "package.json","Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]

collections:
  collections_dir: my_collections
  portfolio:

sass:
  sass_dir: _sass
  style: nested
